name: Robotic Service CD Pipeline

on:
  workflow_run:
    workflows: ['Robotic Service CI Pipeline']
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Setting up environment variables
        run: |
          touch .env
          echo "${{ secrets.ENV_FILE }}" > .env
          touch encryption-public-key.pem
          echo "${{ secrets.ENCRYPTION_PUBLIC_KEY }}" > encryption-public-key.pem
          touch encryption-private-key.pem
          echo "${{ secrets.ENCRYPTION_PRIVATE_KEY }}" > encryption-private-key.pem

      - name: Pull Docker Image
        run: sudo docker pull kenliau0329/robotic-backend:latest

      - name: Remote the existing container
        run: sudo docker rm -f robotic-backend || true

      - name: Run new docker container
        run: sudo docker run -d -p 8080:8080 --name robotic-backend --restart unless-stopped --env-file ./.env kenliau0329/robotic-backend

      - name: Patch secret file
        run: |
          sudo docker cp encryption-public-key.pem robotic-backend:/usr/app/encryption-public-key.pem
          sudo docker cp encryption-private-key.pem robotic-backend:/usr/app/encryption-private-key.pem
