name: Robotic Portal CD Pipeline

on:
  workflow_run:
    workflows: ['Robotic Portal CI Pipeline']
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Run the docker image in container
        run: docker-compose up
