name: Robotic Portal CD Pipeline

on:
  workflow_run:
    workflows: ['Robotic Portal CI Pipeline']
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull Docker Image
        run: sudo docker pull kenliau0329/robotic-backend:latest

      - name: Remote the existing container
        run: sudo docker rm -f robotic-backend || true

      - name: Run new docker container
        run: sudo docker run -d -p 8080:8080 --name robotic-backend --env-file ./.env kenliau0329/robotic-backend
