name: Robotic Portal CI Pipeline

on:
  push:
    branches: ['uat', 'master']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setting up environment variables
        run: |
          touch .env
          echo "${{ secrets.UAT_ENV_FILE }}" > .env
          touch encryption-public-key.pem
          echo "${{ secrets.UAT_PUBLIC_KEY }}" > encryption-public-key.pem
          touch encryption-private-key.pem
          echo "${{ secrets.UAT_PRIVATE_KEY }}" > encryption-private-key.pem

      - name: Login Docker Hub
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build the Docker image
        run: docker build -t kenliau0329/robotic-backend .

      - name: Push to Docker Hub
        run: docker push kenliau0329/robotic-backend:latest
