name: Robotic Portal CI/CD

on:
  push:
    branches: ['uat']

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - run: |
          touch .env
          echo "${{ secrets.UAT_ENV_FILE }}" > .env
          # touch encryption-public-key.pem
          # echo "${{ secrets.UAT_PUBLIC_KEY }}" > encryption-public-key.pem
          # touch encryption-private-key.pem
          # echo "${{ secrets.UAT_PRIVATE_KEY }}" > encryption-private-key.pem
      - run: npm run start
