name: Robotic Portal CI/CD

on:
  push:
    branches: ['uat', 'master']

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install with package-lock
        run: npm ci

      - name: Compile with typescript
        run: npm run build

      - name: Set env for UAT
        if: endsWith(github.ref, '/uat')
        run: |
          touch .env
          echo "${{ secrets.UAT_ENV_FILE }}" > .env
          touch encryption-public-key.pem
          echo "${{ secrets.UAT_PUBLIC_KEY }}" > encryption-public-key.pem
          touch encryption-private-key.pem
          echo "${{ secrets.UAT_PRIVATE_KEY }}" > encryption-private-key.pem

      - name: Set env for PRODUCTION
        if: endsWith(github.ref, '/master')
        run: |
          touch .env
          echo "${{ secrets.MASTER_ENV_FILE }}" > .env
          touch encryption-public-key.pem
          echo "${{ secrets.MASTER_PUBLIC_KEY }}" > encryption-public-key.pem
          touch encryption-private-key.pem
          echo "${{ secrets.MASTER_PRIVATE_KEY }}" > encryption-private-key.pem

      # NOTE: undo this after ec2 instance being finalize
      # - name: Start Server
      #   run: pm2 restart RoboticService
